version: '3'
services:
  web:
    constante_name: "node"
    working_dir: /app 
    ports:
    - "1042:1042"
    - "35729:35729"
    volumes:
    - .:/app/
    image: jjhoncv/orbis-training-docker:1.0.0
    command: npm run start